### ISSUE TITLE
Non generic types Buffer & Uint8Array

### ISSUE THREAD

**Issue by jvanes-awaze** [smithy-lang/smithy-typescript#1675]
After upgrading our project to:
``` 
    "typescript": "~5.6.3",
    "@smithy/core": "^3.9.0",
```

The following errors started showing on running `tsc`

```
node_modules/@smithy/core/dist-types/submodules/cbor/cbor-types.d.ts:40:46 - error TS2315: Type 'Uint8Array' is not generic.

40 export declare function alloc(size: number): Uint8Array<ArrayBuffer> | Buffer<ArrayBuffer>;
                                                ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@smithy/core/dist-types/submodules/cbor/cbor-types.d.ts:40:72 - error TS2315: Type 'Buffer' is not generic.

40 export declare function alloc(size: number): Uint8Array<ArrayBuffer> | Buffer<ArrayBuffer>;
                                                                          ~~~~~~~~~~~~~~~~~~~

node_modules/@smithy/core/dist-types/submodules/cbor/cbor.d.ts:13:28 - error TS2315: Type 'Uint8Array' is not generic.

13     serialize(input: any): Uint8Array<ArrayBufferLike>;
```

Updating the types seems to resolve the issues

**Comment by Lemour-sudo** [comment]
Experiencing a similar issue too after upgrading to 3.9.0

**Comment by kuhe** [comment]
TypeScript's built-in declarations mark Uint8Array as generic for es5 and our target level of es2015. However, it's not our intention to use Uint8Array in a generic way. 

The source code is:

```ts
export function alloc(size: number) {
  return typeof Buffer !== "undefined" ? Buffer.alloc(size) : new Uint8Array(size);
}
```

this was compiled by TS into:

```ts
export declare function alloc(size: number): Uint8Array<ArrayBuffer> | Buffer<ArrayBuffer>;
```

This was due to an implicit return type. I will change it to the following:

```ts
export function alloc(size: number): Uint8Array {
  return typeof Buffer !== "undefined" ? Buffer.alloc(size) : new Uint8Array(size);
}
```
```ts
export declare function alloc(size: number): Uint8Array;
```

**Comment by kuhe** [comment]
The fix was published to https://www.npmjs.com/package/@smithy/core/v/3.9.2

**Comment by jldlslopez** [comment]
> The fix was published to https://www.npmjs.com/package/@smithy/core/v/3.9.2

Error still presents even using v3.9.2: 

node_modules/@smithy/core/dist-types/submodules/cbor/cbor.d.ts:13:28 - error TS2315: Type 'Uint8Array' is not generic.

13     serialize(input: any): Uint8Array<ArrayBufferLike>;

**Comment by jamitchellcb** [comment]
having the same issue. we were using typescript version 5.4.5 and was only able to fix this by upgrading to 5.9.2. Please add another condition to your typesVersions so that upgrading our typescript is optional; currently all versions I tested of @smithy/core (3.7.1, 3.8.0, 3.9.0) are broken on older versions of typescript for which they used to work.

**Comment by jldlslopez** [comment]
> Could you update TypeScript to a later version that has this feature? [microsoft/TypeScript#59417](https://github.com/microsoft/TypeScript/pull/59417)
> 
> This looks like it's available in the 5.7 release. https://github.com/microsoft/TypeScript/blame/release-5.7/src/lib/es5.d.ts

package.json devDependencies updated from
```json
"devDependencies": {
"typescript": "~5.2.2",
...
}
```
to
```json
"devDependencies": {
"typescript": "~5.7.0",
...
}
```
Issue was solved!
 
In resume, the @aws-sdk/core in our project now uses @smithy/core@3.9.2 and we updated the package.json to use typescript v5.7.0
 
Thanks by your support @kuhe

**Comment by Lemour-sudo** [comment]
Updating to typescript 5.9.2 helped.

**Comment by kuhe** [comment]
I do recommend updating typescript to a recent or latest version, but also made more changes in https://github.com/smithy-lang/smithy-typescript/pull/1697 to, at least for now, enforce that we don't emit types with parametric `Uint8Array`s.

It will be released as a patch to the affected packages shortly.
